import Head from "next/head";
import CompanyForm from "../components/company/Company";
import styles from "../styles/Home.module.css";

export default function Company() {
      return (
        <>
        <Head>
        <title>Create company</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          <main className={styles.main}>
            <CompanyForm />
          </main>
        </>
      )
}
    