import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Company() {
    // console.log(getUsers(db).then(response => console.log(response)
    // ));
    // console.log(updateUser().then(response => console.log(response)))
    
      return (
        <>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          <main className={styles.main}>
            <h3>Select company:</h3>
          </main>
        </>
      )
}
    