import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import { deleteUser, getUsers, updateUser } from "../utils/userApi";
import db from "../firebase/firebaseConfig";
import { addUser } from "../utils/userApi";
import Form from "../components/form/Form";
import Router, { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  console.log(getUsers(db).then((response) => console.log(response)));
  // console.log(updateUser().then(response => console.log(response)))
  const router = useRouter();
  console.log(router);
  const handleClick = (e) => {
    e.preventDefault();
    router.push('/company')
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Form />
        <button onClick={handleClick}>
          Company page
        </button>
        <button onClick={updateUser}>remove from company</button>
        <button onClick={deleteUser}>delete</button>
      </main>
    </>
  );
}
