import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import { getUsers } from '../utils/userApi'
import db from '../firebase/firebaseConfig'
import { addUser } from '../utils/userApi'
import Form from '../components/form/Form'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [userInfo, setUserInfo] = useState<any>([]);

  useEffect(() => {
     //Call API function and store data to state
     const getUserData = async () => {
      await getUsers(db).then(data =>{
        if(!data){
          console.log("something went wrong...")
          return;
        }
        setUserInfo(data);
        console.log(data);
      });
    };

    getUserData();
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Form />
        <button onClick={addUser}>Click</button>
      </main>
    </>
  )
}
